In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [4]:
type(a)

numpy.ndarray

In [5]:
b = np.array([3,4,5])

In [6]:
b

array([3, 4, 5])

In [7]:
type(b)

numpy.ndarray

In [8]:
x = np.zeros((2,3,4))

In [9]:
x

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [10]:
x = np.zeros((3,4))

In [11]:
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
type(x)

numpy.ndarray

In [13]:
type(x.dtype)

numpy.dtype

In [14]:
x.shape

(3, 4)

In [15]:
np.zeros(3)

array([0., 0., 0.])

In [16]:
y = np.ones( (3,4), dtype=np.float64)

In [17]:
y

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
y1 = np.ones( (3,4))

In [21]:
y1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
y2 = np.ones( (3,4), dtype=np.int)

In [23]:
y2

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [24]:
print(x.dtype)

float64


In [25]:
print(y.dtype)

float64


In [26]:
print(y1.dtype)

float64


In [27]:
print(y2.dtype)

int64


In [28]:
np.full( (3,4), 0.23)

array([[0.23, 0.23, 0.23, 0.23],
       [0.23, 0.23, 0.23, 0.23],
       [0.23, 0.23, 0.23, 0.23]])

In [30]:
np.full( (3,4), np.pi)

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265]])

In [31]:
np.arange(10,30,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [32]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [33]:
np.arange(1, 10,20)

array([1])

In [34]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [35]:
np.linspace(1,20,2)

array([ 1., 20.])

In [36]:
np.linspace(1,20,20)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20.])

In [37]:
np.random.rand(2,3)

array([[0.93785174, 0.64844781, 0.25095605],
       [0.38273136, 0.60952499, 0.73039552]])

In [38]:
x = np.empty( (2,3))

In [39]:
x

array([[0.93785174, 0.64844781, 0.25095605],
       [0.38273136, 0.60952499, 0.73039552]])

In [40]:
c = np.arange(1,5)

In [41]:
c

array([1, 2, 3, 4])

In [42]:
c = np.arange(1,5,1)

In [43]:
c

array([1, 2, 3, 4])

In [44]:
a = np.arange(6)

In [45]:
a

array([0, 1, 2, 3, 4, 5])

In [46]:
b = a.reshape(2,3)

In [47]:
b

array([[0, 1, 2],
       [3, 4, 5]])

In [51]:
%

UsageError: Line magic function `%` not found.


In [52]:
%a

UsageError: Line magic function `%a` not found.


In [1]:
import pandas as pd

In [4]:
a = pd.Series([2,-1,4,5])

In [5]:
a

0    2
1   -1
2    4
3    5
dtype: int64

In [6]:
a+1000

0    1002
1     999
2    1004
3    1005
dtype: int64

In [7]:
a

0    2
1   -1
2    4
3    5
dtype: int64

In [8]:
a<0

0    False
1     True
2    False
3    False
dtype: bool

In [10]:
a2 = pd.Series([68,83,112,68])

In [11]:
a2

0     68
1     83
2    112
3     68
dtype: int64

In [13]:
a2 = pd.Series([68,83,112,68], index=("alice", "bob", "charles", "darwin"))

In [14]:
a2

alice       68
bob         83
charles    112
darwin      68
dtype: int64

In [1]:
import numpy as np

In [2]:
my_list = [50, 12, 67, 23]

In [3]:
my_list_array = np.array(my_list)

In [4]:
print(my_list_array)

[50 12 67 23]


In [5]:
type(my_list_array)

numpy.ndarray

In [6]:
my_tup = (88, 17, 45, 76)

In [7]:
my_tup_arr = np.array(my_tup)

In [8]:
print(my_tup_arr)

[88 17 45 76]


In [9]:
sample_list = [1, 2, 3]

In [10]:
list_array = np.array(sample_list)

In [11]:
list_array

array([1, 2, 3])

In [12]:
print(list_array)

[1 2 3]


In [13]:
tup = (1, 2, 3)

In [14]:
my_tup_array = np.array(tup)

In [15]:
print(my_tup_array)

[1 2 3]


In [22]:
def multiply_loops(A, B):
    c = np.zeros((A.shape[0], B.shape[1]))
    for i in range(A.shape[0]):
        for k in range(B.shape[1]):
            c[i,k] = 0
            for j in range(B.shape[0]):
                n = A[i,j] * B[j,k]
                c[i,k] += n
    return c

In [23]:
def multiply_vector(A,B):
    return A @ B

In [24]:
X = np.random.random((100,100))
Y = np.random.random((100,100))

In [25]:
%timeit multiply_loops(X,Y)
%timeit multiply_vector(X,Y)

857 ms ± 19.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
75.9 µs ± 6.27 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [26]:
tup_dim = (3,4)

In [67]:
my_zeros_array = np.zeros(tup_dim, dtype=np.int16)

In [68]:
my_zeros_array

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)

In [69]:
print(my_zeros_array)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [30]:
tup_dim = (3, 4)

In [70]:
my_ones_array = np.ones(tup_dim, dtype=np.int16)

In [71]:
my_ones_array

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [72]:
print(my_ones_array)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [34]:
tup_dim = (3, 4)

In [35]:
my_seven_array = np.full(tup_dim, 7, dtype=np.int16)

In [36]:
my_seven_array

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]], dtype=int16)

In [37]:
print(my_seven_array)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [38]:
my_identity_array = np.identity(4, dtype=np.float64)

In [39]:
my_identity_array

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [40]:
print(my_identity_array)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [97]:
my_rand_array = np.random.rand(3,4)

In [98]:
my_rand_array

array([[0.40923774, 0.7898188 , 0.31776305, 0.10767965],
       [0.09374105, 0.96906299, 0.05961899, 0.50121043],
       [0.67706148, 0.52350956, 0.1962101 , 0.34154773]])

In [99]:
print(my_rand_array)

[[0.40923774 0.7898188  0.31776305 0.10767965]
 [0.09374105 0.96906299 0.05961899 0.50121043]
 [0.67706148 0.52350956 0.1962101  0.34154773]]


In [101]:
tup_dim = (3,4)

In [102]:
my_uninitialized_array = np.empty( tup_dim )

In [105]:
my_uninitialized_array

array([[0.40923774, 0.7898188 , 0.31776305, 0.10767965],
       [0.09374105, 0.96906299, 0.05961899, 0.50121043],
       [0.67706148, 0.52350956, 0.1962101 , 0.34154773]])

In [115]:
my_range_array = np.arange(10, 30, 5)

In [116]:
my_range_array

array([10, 15, 20, 25])

In [117]:
my_spaced_array = np.linspace(0, 5/3, 6)

In [118]:
my_spaced_array

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667])

In [128]:
array_A = np.array([ [3,4,6], [0,8,1] ])

In [132]:
my_array = np.array([ [1,4,5,6], [7,8,9,10], [11,12,14,16] ])

In [142]:
my_array.ndim()

TypeError: 'int' object is not callable

In [143]:
my_array.ndim

2

In [144]:
my_array.shape

(3, 4)

In [145]:
my_array.dtype

dtype('int64')

In [146]:
my_array.size

12

In [147]:
import numpy as np
import os

In [148]:
import pandas as pd

In [149]:
#defining housing.csv filepath
HOUSING_PATH = '/cxldata/datasets/project/housing'
#reading the large housing.csv file using pandas
housing_raw = pd.read_csv(os.path.join(HOUSING_PATH, "housing.csv"))
#extracting only a few rows(5 rows) of data from the pandas dataframe 'my_df'
my_df = housing_raw.iloc[ : 5]
#creating a new small csv file - 'housing_short.csv' - containing the above extracted 5 rows of data
my_df.to_csv('housing_short.csv', index=False)

In [152]:
FILE = "housing_short.csv"

In [153]:
def load_housing_data(file = FILE):
    return np.loadtxt(file, dtype={'names': ('longitude','latitude', 'housing_median_age', 'total_rooms', 'total_bedrooms',
        'population','households','median_income','median_house_value','ocean_proximity'), 'formats': ('f8', 'f8', 'f8', 'f8', 'f8', 'f8', 'f8', 'f8', 'f8', '|S15')}, 
                     delimiter=',', skiprows=1, unpack=True)

In [157]:
longitude_arr,latitude_arr,housing_median_age_arr,total_rooms_arr,total_bedrooms_arr,population_arr,households_arr,median_income_arr,median_house_value_arr,ocean_proximity_arr = load_housing_data()

In [158]:
print(median_house_value_arr)

[452600. 358500. 352100. 341300. 342200.]


In [167]:
import numpy as np
import os

In [168]:
HOUSING_PATH = '/cxldata/datasets/project/housing'

In [169]:
FILE = os.path.join(HOUSING_PATH, 'housing.csv')

In [170]:
FILE

'/cxldata/datasets/project/housing/housing.csv'

In [172]:
def load_housing_dataset(file = FILE):
    return np.genfromtxt(file, dtype={'names': ('longitude','latitude','housing_median_age','total_rooms','total_bedrooms',
                                                'population','households','median_income','median_house_value','ocean_proximity'),
                                      'formats': ('f8', 'f8', 'f8', 'f8', 'f8', 'f8', 'f8', 'f8', 'f8', '|S15')}, 
                                         delimiter=',', skip_header=1, filling_values = 99999999, unpack=False)


In [173]:
result_arr = load_housing_dataset()

In [174]:
print(result_arr)

[(-122.23, 37.88, 41.,  880.,  129.,  322.,  126., 8.3252, 452600., b'NEAR BAY')
 (-122.22, 37.86, 21., 7099., 1106., 2401., 1138., 8.3014, 358500., b'NEAR BAY')
 (-122.24, 37.85, 52., 1467.,  190.,  496.,  177., 7.2574, 352100., b'NEAR BAY')
 ...
 (-121.22, 39.43, 17., 2254.,  485., 1007.,  433., 1.7   ,  92300., b'INLAND')
 (-121.32, 39.43, 18., 1860.,  409.,  741.,  349., 1.8672,  84700., b'INLAND')
 (-121.24, 39.37, 16., 2785.,  616., 1387.,  530., 2.3886,  89400., b'INLAND')]


In [175]:
print(len(result_arr))

20640


In [182]:
import numpy as np
my_arr = np.array([ [0,1], [2,3] ])
print(my_arr)
my_arr.resize( (2,3) )
print(my_arr)

[[0 1]
 [2 3]]
[[0 1 2]
 [3 0 0]]


In [198]:
my_arr = np.array([ [1,2,3,4], [5,6,7,8]])

In [199]:
my_arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [200]:
np.resize(my_arr, (3,4))

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [204]:
my_arr = np.arange(6)
print(my_arr)

[0 1 2 3 4 5]


In [205]:
my_new_array = my_arr.reshape(2,3)

In [206]:
my_new_array

array([[0, 1, 2],
       [3, 4, 5]])

In [207]:
my_arr = np.arange(9)

In [208]:
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [209]:
my_new_arr = my_arr.reshape(-1,3)

In [210]:
my_new_arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [211]:
my_arr = np.arange(8)
print(my_arr)

[0 1 2 3 4 5 6 7]


In [212]:
my_arr.reshape(2,3)

ValueError: cannot reshape array of size 8 into shape (2,3)

In [213]:
my_arr.reshape(3,3)

ValueError: cannot reshape array of size 8 into shape (3,3)

In [214]:
my_arr.reshape(-1,3)

ValueError: cannot reshape array of size 8 into shape (3)

In [215]:
import numpy as np

In [216]:
my_first_arr = np.arange(1,9)

In [217]:
my_first_arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [218]:
my_new_arr = my_first_arr.reshape(2,4)

In [219]:
my_new_arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [220]:
print(my_new_arr)

[[1 2 3 4]
 [5 6 7 8]]


In [221]:
print(my_first_arr)

[1 2 3 4 5 6 7 8]


In [225]:
my_second_arr = np.array([0,1,2,3,4,5,6,7,8])

In [226]:
my_second_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [227]:
my_updated_arr = my_second_arr.reshape(-1,3)

In [228]:
print(my_updated_arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [229]:
print(my_second_arr)

[0 1 2 3 4 5 6 7 8]


In [239]:
arr = np.array([1,10,31,2,18,9,22])

In [240]:
print(arr[1])

10


In [241]:
part_arr = arr[2:5]

In [242]:
part_arr

array([31,  2, 18])

In [243]:
skip_arr = arr[1: :2]

In [244]:
skip_arr

array([10,  2,  9])

In [245]:
my_orig_arr = np.array([1,15,3,9,26,7,89,12])

In [246]:
my_rev_arr = my_orig_arr[::-1]

In [247]:
print(my_rev_arr)

[12 89  7 26  9  3 15  1]


In [248]:
my_orig_arr2 = np.array([2,9,17,13,1,4,20,57])

In [249]:
my_orig_arr2

array([ 2,  9, 17, 13,  1,  4, 20, 57])

In [250]:
my_orig_arr2[2:5] = -6

In [251]:
my_orig_arr2

array([ 2,  9, -6, -6, -6,  4, 20, 57])

In [252]:
print(my_orig_arr2)

[ 2  9 -6 -6 -6  4 20 57]


In [253]:
arr = [1,3,5,10,4,15]

In [254]:
arr[1:4] = -3

TypeError: can only assign an iterable

In [255]:
apple = np.array([1,8,23,3,18,91,7,15])

In [256]:
apple

array([ 1,  8, 23,  3, 18, 91,  7, 15])

In [257]:
apple_slice = apple[1:4]

In [258]:
print(apple_slice)

[ 8 23  3]


In [259]:
print(apple)

[ 1  8 23  3 18 91  7 15]


In [260]:
apple_slice[1] = 99999

In [261]:
print(apple_slice)

[    8 99999     3]


In [262]:
print(apple)

[    1     8 99999     3    18    91     7    15]


In [263]:
apple_slice_new = apple[2:5].copy()

In [264]:
apple_slice_new

array([99999,     3,    18])

In [265]:
apple_slice_new[1] = 222222

In [266]:
print(apple_slice_new)

[ 99999 222222     18]


In [267]:
print(apple)

[    1     8 99999     3    18    91     7    15]


In [277]:
import load_sample_image from sklearn.datasets

SyntaxError: invalid syntax (<ipython-input-277-96aecbd5eed7>, line 1)

In [280]:
from sklearn.datasets import load_sample_image

In [281]:
china = load_sample_image("china.jpg")

In [282]:
china

array([[[174, 201, 231],
        [174, 201, 231],
        [174, 201, 231],
        ...,
        [250, 251, 255],
        [250, 251, 255],
        [250, 251, 255]],

       [[172, 199, 229],
        [173, 200, 230],
        [173, 200, 230],
        ...,
        [251, 252, 255],
        [251, 252, 255],
        [251, 252, 255]],

       [[174, 201, 231],
        [174, 201, 231],
        [174, 201, 231],
        ...,
        [252, 253, 255],
        [252, 253, 255],
        [252, 253, 255]],

       ...,

       [[ 88,  80,   7],
        [147, 138,  69],
        [122, 116,  38],
        ...,
        [ 39,  42,  33],
        [  8,  14,   2],
        [  6,  12,   0]],

       [[122, 112,  41],
        [129, 120,  53],
        [118, 112,  36],
        ...,
        [  9,  12,   3],
        [  9,  15,   3],
        [ 16,  24,   9]],

       [[116, 103,  35],
        [104,  93,  31],
        [108, 102,  28],
        ...,
        [ 43,  49,  39],
        [ 13,  21,   6],
        [ 15,  24,   7]]

In [283]:
portion = china[120:250, 110:230]

In [284]:
portion

array([[[ 62,  61,  56],
        [ 25,  22,  15],
        [ 28,  29,  21],
        ...,
        [ 21,  27,  23],
        [ 25,  25,  23],
        [ 18,  13,  10]],

       [[ 33,  34,  29],
        [ 24,  24,  16],
        [ 38,  39,  33],
        ...,
        [ 21,  25,  24],
        [ 26,  24,  25],
        [ 29,  23,  25]],

       [[  3,   3,   1],
        [ 15,  14,  10],
        [ 29,  30,  25],
        ...,
        [ 30,  31,  33],
        [ 18,  16,  19],
        [ 20,  15,  19]],

       ...,

       [[ 35,  32,  25],
        [ 32,  32,  24],
        [ 28,  22,  22],
        ...,
        [ 70,  81,  85],
        [ 76,  88,  86],
        [ 93,  86,  68]],

       [[ 52,  51,  33],
        [ 52,  46,  20],
        [ 50,  43,  25],
        ...,
        [ 72,  76,  88],
        [ 94,  99, 105],
        [122, 104,  84]],

       [[ 58,  60,  39],
        [ 63,  62,  34],
        [ 65,  67,  46],
        ...,
        [ 90, 104, 105],
        [103, 119, 119],
        [127, 126, 108]]

In [285]:
print(portion)

[[[ 62  61  56]
  [ 25  22  15]
  [ 28  29  21]
  ...
  [ 21  27  23]
  [ 25  25  23]
  [ 18  13  10]]

 [[ 33  34  29]
  [ 24  24  16]
  [ 38  39  33]
  ...
  [ 21  25  24]
  [ 26  24  25]
  [ 29  23  25]]

 [[  3   3   1]
  [ 15  14  10]
  [ 29  30  25]
  ...
  [ 30  31  33]
  [ 18  16  19]
  [ 20  15  19]]

 ...

 [[ 35  32  25]
  [ 32  32  24]
  [ 28  22  22]
  ...
  [ 70  81  85]
  [ 76  88  86]
  [ 93  86  68]]

 [[ 52  51  33]
  [ 52  46  20]
  [ 50  43  25]
  ...
  [ 72  76  88]
  [ 94  99 105]
  [122 104  84]]

 [[ 58  60  39]
  [ 63  62  34]
  [ 65  67  46]
  ...
  [ 90 104 105]
  [103 119 119]
  [127 126 108]]]


In [1]:
import numpy as np
from sklearn.datasets import load_sample_image

In [2]:
china = load_sample_image("china.jpg")

In [3]:
china.shape

(427, 640, 3)

In [4]:
china

array([[[174, 201, 231],
        [174, 201, 231],
        [174, 201, 231],
        ...,
        [250, 251, 255],
        [250, 251, 255],
        [250, 251, 255]],

       [[172, 199, 229],
        [173, 200, 230],
        [173, 200, 230],
        ...,
        [251, 252, 255],
        [251, 252, 255],
        [251, 252, 255]],

       [[174, 201, 231],
        [174, 201, 231],
        [174, 201, 231],
        ...,
        [252, 253, 255],
        [252, 253, 255],
        [252, 253, 255]],

       ...,

       [[ 88,  80,   7],
        [147, 138,  69],
        [122, 116,  38],
        ...,
        [ 39,  42,  33],
        [  8,  14,   2],
        [  6,  12,   0]],

       [[122, 112,  41],
        [129, 120,  53],
        [118, 112,  36],
        ...,
        [  9,  12,   3],
        [  9,  15,   3],
        [ 16,  24,   9]],

       [[116, 103,  35],
        [104,  93,  31],
        [108, 102,  28],
        ...,
        [ 43,  49,  39],
        [ 13,  21,   6],
        [ 15,  24,   7]]

In [5]:
image = china[150:220, 130:250]

In [6]:
image.shape

(70, 120, 3)

In [7]:
height, width, channels = image.shape

In [8]:
height, width, channels

(70, 120, 3)

In [9]:
height

70

In [23]:
image_grayscale = image.mean(axis=2).astype(np.float32)

In [24]:
image_grayscale.shape

(70, 120)

In [25]:
images = image_grayscale.reshape(1, height, width, 1)

In [26]:
images.ndim

4

In [2]:
import numpy as np

In [3]:
multi_arr = np.arange(12).reshape(3,4)

In [4]:
multi_arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [8]:
np.arange(12).reshape(6,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [9]:
multi_arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
rows_wanted = np.array( [True, False, True])

In [11]:
rows_wanted

array([ True, False,  True])

In [12]:
multi_arr_portion = multi_arr[rows_wanted, : ]

In [13]:
multi_arr_portion

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [14]:
import numpy as np

In [15]:
my_multi_arr = np.arange(20).reshape(4,5)

In [16]:
my_multi_arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [17]:
my_multi_arr_portion = my_multi_arr[2:4, 2:5]

In [18]:
my_multi_arr_portion

array([[12, 13, 14],
       [17, 18, 19]])

In [19]:
print(my_multi_arr_portion)

[[12 13 14]
 [17 18 19]]


In [26]:
my_2d_arr = np.arange(20).reshape(4,5)

In [27]:
my_2d_arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [28]:
my_1d_arr = my_2d_arr.ravel()

In [29]:
print(my_1d_arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [36]:
a_arr = np.array([60,70,80,90])
b_arr = np.arange(4)

In [37]:
a_arr

array([60, 70, 80, 90])

In [38]:
b_arr

array([0, 1, 2, 3])

In [39]:
c_arr = a_arr + b_arr

In [40]:
c_arr

array([60, 71, 82, 93])

In [41]:
print(c_arr)

[60 71 82 93]


In [63]:
d_arr = np.array([60,70,80,90])
e_arr = np.arange(4)

In [64]:
d_arr

array([60, 70, 80, 90])

In [65]:
e_arr

array([0, 1, 2, 3])

In [66]:
f_arr = d_arr - e_arr

In [67]:
print(f_arr)

[60 69 78 87]


In [84]:
A_arr = np.array([ [5,9], [4,7] ])
B_arr = np.array([ [2,8], [1,6] ])

In [85]:
M_arr = A_arr * B_arr

In [86]:
print(M_arr)

[[10 72]
 [ 4 42]]


In [87]:
C_arr = np.array([ [5,9], [4,7] ])
D_arr = np.array([ [2,8], [1,6] ])

In [88]:
P_arr = np.dot(C_arr, D_arr)

In [89]:
print(P_arr)

[[19 94]
 [15 74]]


In [106]:
R_div = np.array([ [25,65], [40,14] ])
S_div = np.array([ [2,10], [4,5] ])

In [107]:
T_div = R_div / S_div

In [108]:
print(T_div)

[[12.5  6.5]
 [10.   2.8]]


In [109]:
R_int_div = np.array([ [ 25,65], [40, 70] ])
S_int_div = np.array([ [2, 10], [8, 3] ] )

In [110]:
T_int_div = R_int_div // S_int_div

In [111]:
print(T_int_div)

[[12  6]
 [ 5 23]]


In [112]:
R_mod = np.array([ [ 20,65], [40, 70] ])
S_mod = np.array([ [2, 10], [8, 3] ] )

In [113]:
T_mod = R_mod % S_mod

In [114]:
print(T_mod)

[[0 5]
 [0 1]]


In [133]:
import numpy as np
R_exp = np.array( [20,20,40,50])
S_exp = np.arange(1,5)

T_exp = R_exp ** S_exp



In [134]:
print(R_exp)

[20 20 40 50]


In [135]:
print(S_exp)

[1 2 3 4]


In [136]:
print(T_exp)

[     20     400   64000 6250000]


In [137]:
T_exp

array([     20,     400,   64000, 6250000])

In [138]:
R_exp = np.array([ [ 4, 2], [3, 4 ] ] )
S_exp = np.array( [ [2, 10], [4, 5] ] )

In [139]:
T_exp = R_exp ** S_exp

In [140]:
print(T_exp)

[[  16 1024]
 [  81 1024]]


In [149]:
U = np.array([ [ 22, 45], [90, 4 ] ] )

In [150]:
print(U[U<45])

[22  4]


In [156]:
X_stat = np.array([ [ 1, 2, 3], [ 4, -5, 6] ])

In [157]:
X_stat

array([[ 1,  2,  3],
       [ 4, -5,  6]])

In [158]:
print("mean = ", X_stat.mean())

mean =  1.8333333333333333


In [159]:
print("Variance = ", X_stat.var())

Variance =  11.805555555555557


In [160]:
print("Standard Deviation = ", X_stat.std())

Standard Deviation =  3.435921354681384


In [162]:
print("min = ", X_stat.min())

min =  -5


In [164]:
print("max = ", X_stat.max())

max =  6


In [165]:
print("sum = ", X_stat.sum())

sum =  11


In [166]:
print("product = ", X_stat.prod())

product =  -720


In [179]:
Z = np.arange(18).reshape(2,3,3)

In [180]:
Z

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [181]:
print(Z)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]


In [182]:
print( Z.sum(axis=2))

[[ 3 12 21]
 [30 39 48]]


In [188]:
M = np.arange(6).reshape(2, 3)

In [189]:
M

array([[0, 1, 2],
       [3, 4, 5]])

In [190]:
M.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [191]:
N = np.arange(6).reshape(3,2)

In [192]:
N

array([[0, 1],
       [2, 3],
       [4, 5]])

In [193]:
print(N)

[[0 1]
 [2 3]
 [4 5]]


In [194]:
print("Transpose = ", N.T)

Transpose =  [[0 2 4]
 [1 3 5]]


In [204]:
X_broad = np.ones((3,3))

In [205]:
print(X_broad)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [206]:
Y_broad = np.arange(3)

In [207]:
print(Y_broad)

[0 1 2]


In [209]:
Z_broad = X_broad + Y_broad

In [210]:
print(Z_broad)

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
